/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatorio2restoUIEscritorio;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import obligatorio2restoControladores.ControladorVistaMozo;
import obligatoriorestoLogica.Mesa;
import obligatoriorestoLogica.Mozo;

/**
 *
 * @author tomas
 */
public class TransferenciaMesa extends javax.swing.JFrame {
    
   private Mesa mesa;
   private ArrayList<Mozo> mozosConectados;
   private Mozo mozoTransferir;
   private ControladorVistaMozo controlador;
    

    /**
     * Creates new form TransferenciaMesa
     */
    public TransferenciaMesa(ArrayList<Mozo> mozos,Mesa mesaTransferir) {
        initComponents();
        mostrarMozosConectados(mozos);
        mozosConectados=mozos;
        mesa=mesaTransferir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMozosConectados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonTransferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Transferir Mesa");

        jTableMozosConectados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMozosConectados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMozosConectadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMozosConectados);

        jLabel2.setText("Mozos conectados:");

        jButtonTransferir.setText("Transferir");
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTransferir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel2))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButtonTransferir)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        transferirMesa(mesa,mozoTransferir);
    }//GEN-LAST:event_jButtonTransferirActionPerformed

    private void jTableMozosConectadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMozosConectadosMouseClicked
        mozoTransferir=seleccionarMozo(jTableMozosConectados.getSelectedRow());
    }//GEN-LAST:event_jTableMozosConectadosMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    private Mozo seleccionarMozo(int pos) {
        Mozo elegido = null;
        if (pos != -1) {
            elegido = mozosConectados.get(pos);
        }
        return elegido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMozosConectados;
    // End of variables declaration//GEN-END:variables

    
    public void mostrarMozosConectados(ArrayList<Mozo> mozosConectados){
        
        DefaultTableModel lista = new DefaultTableModel();
        
        lista.addColumn("Nombre Mozo");
        lista.addColumn("Cantidad Mesas Asignadas");
        
        int fila = 0;
            lista.setNumRows(mozosConectados.size());
            
            for(Mozo mo: mozosConectados){
                lista.setValueAt(mo.getNombreCompleto(),fila,0);
                lista.setValueAt(mo.getMesas().size(),fila,0);
                fila++;
            }
            jTableMozosConectados.setModel(lista);
    }

    private void transferirMesa(Mesa mesa, Mozo mozoTransferir) {
        controlador.transferirMesa(mesa, mozoTransferir);
    }
}
